[package]
name = "cypher-dto-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
serde = ["serde/derive"]

[dependencies]
convert_case = "0.6.0"
quote = "1"
serde = { version = "1.0", optional = true, features = ["derive"] }
syn = "2"
